#
# SellCube configuration file
#
max_rent_days: 14    # max ammount of days region can be rent
offline_days: 21     # after this time, region is considered abandoned
sign_updater: false  # automatic sign updates every 12 h
colors:
  default: f         # based on name of player primary group
location_groups:
  default:           # permission group name
    default:         # location name
      buy:  1
      rent: 1