name: SellCube
main: pl.bluex.sellcube.SellCube
version: '1.0'
description: Plugin pozwalajacy sprzedawać regiony za pomoca znakow
author: BlueX
depend: [PermissionsEx]
database: true
permissions:
  sellcube.*:
    description: Gives access to all SellCube permissions
    children:
      sellcube.sell_all: true
      sellcube.sell: true
      sellcube.buy: true
      sellcube.lwc_pass: true
  sellcube.sell:
    description: Allows user to create an ad
    default: true
  sellcube.sell_all:
    description: Allows user to create an ad of all regions
    default: op
    children:
      sellcube.sell: true
  sellcube.buy:
    description: Allows user to buy cube
    default: true
  sellcube.lwc_pass:
    description: Allows user to create ad sign which doesn't change owner after purchase
    default: op
  sellcube.tp:
    description: Allows user to teleport to last bought ad
    default: true
  sellcube.find:
    description: Allows user to teleport to first active ad
    default: true
commands:
  sellcube:
    description: Zarządza ogłoszeniami
    aliases: sc
    usage: |
      /<command> add [lp] cena nazwa_regionu - tworzy ogłoszenie
      /<command> copy id - kopiuje ogłoszenie na podstawie id w bazie
      /<command> cancel - anuluje tworzenie ogłoszenia
      /<command> find - teleportuje do pierwszego dostępnego ogłoszenia
      /<command> status - tworzy tabliczkę z informacjami o graczu
      /<command> tp - teleportuje do ostatnio kupionego ogłoszenia
  scadd:
    description: tworzy ogłoszenie
    permission: sellcube.sell
    usage: /<command> add [lp] cena nazwa_regionu
  sccopy:
    description: kopiuje ogłoszenie na podstawie id w bazie
    permission: sellcube.sell
    usage: /<command> copy id
  sccancel:
    description: anuluje tworzenie ogłoszenia
    permission: sellcube.sell
  scstatus:
    description: tworzy tabliczkę z informacjami o graczu
  sctp:
    description: teleportuje do ostatnio kupionego ogłoszenia
    permission: sellcube.tp
  scfind:
    description: teleportuje do pierwszego dostępnego ogłoszenia
    permission: sellcube.find